#!/usr/bin/env python3
"""Robust Android build fixer for VCTCrypt CI.

Patches the android/ scaffolding generated by `flutter create`:
  1. Kotlin Gradle plugin version -> KOTLIN_VERSION (plugin DSL in
     settings.gradle AND legacy ext.kotlin_version in build.gradle)
  2. compileSdk -> 35 (required by recent AndroidX/plugin artifacts)
  3. R8 minify + resource shrinking for anti-decompilation

Every patch is VERIFIED after writing - if anything fails to apply the
script exits non-zero so CI fails loudly instead of silently producing
a broken build.
"""

import re
import sys

KOTLIN_VERSION = "1.9.24"
COMPILE_SDK = "35"

errors = []


def patch(path, patterns, label, required=False):
    """Apply (pattern, replacement) list; return True if any matched.

    A missing file is only fatal when [required] - e.g. a project may
    use EITHER the plugin DSL (settings.gradle) OR the legacy
    ext.kotlin_version (build.gradle), so either one alone is fine.
    """
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        if required:
            errors.append(f"{label}: file not found: {path}")
        return False

    matched = False
    for pattern, replacement in patterns:
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            content = new_content
            matched = True

    if matched:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
    return matched


# ---------------------------------------------------------------
# 1) Kotlin version
# ---------------------------------------------------------------
# New Flutter template (settings.gradle, plugin DSL):
#   id "org.jetbrains.kotlin.android" version "1.8.22" apply false
settings_ok = patch(
    "android/settings.gradle",
    [
        (
            r'(org\.jetbrains\.kotlin\.android["\s]+version\s+)["\'][^"\']+["\']',
            r'\g<1>"' + KOTLIN_VERSION + '"',
        ),
        (
            r'(kotlin-android["\s]+version\s+)["\'][^"\']+["\']',
            r'\g<1>"' + KOTLIN_VERSION + '"',
        ),
    ],
    "Kotlin plugin DSL (settings.gradle)",
)

# Legacy template (build.gradle): ext.kotlin_version = '1.8.22'
legacy_ok = patch(
    "android/build.gradle",
    [
        (
            r"ext\.kotlin_version\s*=\s*['\"][^'\"]*['\"]",
            "ext.kotlin_version = '" + KOTLIN_VERSION + "'",
        )
    ],
    "Kotlin legacy ext (build.gradle)",
)

# Verify: at least one Kotlin declaration must now carry the target version.
kotlin_declared = False
for path in ("android/settings.gradle", "android/build.gradle"):
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read()
        if "org.jetbrains.kotlin.android" in text and KOTLIN_VERSION in text:
            kotlin_declared = True
        if "ext.kotlin_version" in text and KOTLIN_VERSION in text:
            kotlin_declared = True
    except FileNotFoundError:
        pass

if not kotlin_declared:
    errors.append(
        "Kotlin version not verified after patch "
        f"(settings.gradle matched={settings_ok}, build.gradle matched={legacy_ok})"
    )

# ---------------------------------------------------------------
# 2) compileSdk 35
# ---------------------------------------------------------------
compile_ok = patch(
    "android/app/build.gradle",
    [
        (r"compileSdk\s*=\s*\d+", "compileSdk = " + COMPILE_SDK),
        (r"compileSdkVersion\s+\d+", "compileSdkVersion " + COMPILE_SDK),
    ],
    "compileSdk (app/build.gradle)",
    required=True,
)

# ---------------------------------------------------------------
# 3) R8 minify + shrink (anti-decompilation)
# ---------------------------------------------------------------
r8_ok = patch(
    "android/app/build.gradle",
    [
        (r"minifyEnabled\s+false", "minifyEnabled true"),
        (r"shrinkResources\s+false", "shrinkResources true"),
    ],
    "R8 (app/build.gradle)",
)

# Kotlin JVM target validation is a warning, not an error (mixed plugin versions)
try:
    with open("android/gradle.properties", "a", encoding="utf-8") as f:
        f.write("\n# VCTCrypt CI: tolerate mixed Kotlin JVM targets\n")
        f.write("kotlin.jvm.target.validation.mode=warning\n")
except FileNotFoundError:
    errors.append("gradle.properties not found")

# ---------------------------------------------------------------
# Report
# ---------------------------------------------------------------
print("=== fix_android.py report ===")
print(f"Kotlin -> {KOTLIN_VERSION}: " + ("OK" if kotlin_declared else "FAILED"))
print(f"compileSdk -> {COMPILE_SDK}: " + ("patched" if compile_ok else "not found (maybe already set)"))
print(f"R8 minify/shrink: " + ("patched" if r8_ok else "not found (maybe already set)"))

print("\n--- settings.gradle (kotlin/agp lines) ---")
try:
    for line in open("android/settings.gradle", encoding="utf-8"):
        if "kotlin" in line.lower() or "com.android.application" in line:
            print("   " + line.rstrip())
except FileNotFoundError:
    print("   (missing)")

if errors:
    print("\nERRORS:", file=sys.stderr)
    for e in errors:
        print("  - " + e, file=sys.stderr)
    sys.exit(1)

print("\nAll critical patches applied and verified.")
