#!/usr/bin/env python3
"""Robust Android build fixer for VCTCrypt CI.

Patches the android/ scaffolding generated by `flutter create` so the
build works on GitHub runners with the android-35 platform:

  1. Gradle wrapper -> 8.9          (AGP 8.5 requires Gradle >= 8.7)
  2. AGP -> 8.5.0                    (settings.gradle plugin DSL)
  3. Kotlin -> 1.9.24                (plugin DSL + legacy ext)
  4. app compileSdk -> 35            (plugins like flutter_plugin_
                                     android_lifecycle build with SDK 35)
  5. app buildToolsVersion -> 35.0.0 (aapt2 from build-tools <= 34 CANNOT
                                     parse the android-35 android.jar
                                     resources table -> "RES_TABLE_TYPE_TYPE
                                     entry offsets overlap actual entry data")
  6. Force kotlin-gradle-plugin 1.9.24 onto EVERY subproject. Flutter
     plugins ship legacy buildscript blocks with old Kotlin (e.g.
     desktop_drop 0.4.4 uses 1.6.10) which cannot read the metadata of
     modern androidx/kotlin-stdlib artifacts ("Module was compiled with
     an incompatible version of Kotlin"). Gradle buildscript conflict
     resolution keeps the highest version, so injecting 1.9.24 from the
     root project overrides every plugin.
  7. R8 minify + resource shrinking for anti-decompilation.

Every critical patch is VERIFIED after writing - if anything fails the
script exits non-zero so CI fails loudly.
"""

import re
import sys

KOTLIN_VERSION = "1.9.24"
AGP_VERSION = "8.5.0"
GRADLE_VERSION = "8.9"
COMPILE_SDK = "35"
BUILD_TOOLS = "35.0.0"

errors = []


def read(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        return None


def write(path, content):
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def patch(path, patterns, label, required=False):
    """Apply (pattern, replacement) list; return True if any matched."""
    content = read(path)
    if content is None:
        if required:
            errors.append(f"{label}: file not found: {path}")
        return False
    matched = False
    for pattern, replacement in patterns:
        new_content, n = re.subn(pattern, replacement, content)
        if n > 0:
            content = new_content
            matched = True
    if matched:
        write(path, content)
    return matched


# ---------------------------------------------------------------
# 1) Gradle wrapper -> 8.9
# ---------------------------------------------------------------
wrapper_ok = patch(
    "android/gradle/wrapper/gradle-wrapper.properties",
    [
        (
            r"distributionUrl=.*gradle-[0-9.]+(?:-bin|-all)?\.zip",
            "distributionUrl=https\\://services.gradle.org/distributions/"
            f"gradle-{GRADLE_VERSION}-bin.zip",
        )
    ],
    "Gradle wrapper",
    required=True,
)
wrapper_content = read("android/gradle/wrapper/gradle-wrapper.properties") or ""
if f"gradle-{GRADLE_VERSION}" not in wrapper_content:
    errors.append(f"Gradle wrapper not verified at {GRADLE_VERSION}")

# ---------------------------------------------------------------
# 2) AGP -> 8.5.0  (settings.gradle plugin DSL)
# ---------------------------------------------------------------
agp_ok = patch(
    "android/settings.gradle",
    [
        (
            r'(com\.android\.application["\s]+version\s+)["\'][^"\']+["\']',
            r'\g<1>"' + AGP_VERSION + '"',
        )
    ],
    "AGP (settings.gradle)",
    required=True,
)
settings_content = read("android/settings.gradle") or ""
if "com.android.application" in settings_content and AGP_VERSION not in settings_content:
    errors.append(f"AGP version not verified at {AGP_VERSION}")

# ---------------------------------------------------------------
# 3) Kotlin -> 1.9.24  (plugin DSL and legacy ext)
# ---------------------------------------------------------------
patch(
    "android/settings.gradle",
    [
        (
            r'(org\.jetbrains\.kotlin\.android["\s]+version\s+)["\'][^"\']+["\']',
            r'\g<1>"' + KOTLIN_VERSION + '"',
        ),
        (
            r'(kotlin-android["\s]+version\s+)["\'][^"\']+["\']',
            r'\g<1>"' + KOTLIN_VERSION + '"',
        ),
    ],
    "Kotlin plugin DSL (settings.gradle)",
)
patch(
    "android/build.gradle",
    [
        (
            r"ext\.kotlin_version\s*=\s*['\"][^'\"]*['\"]",
            "ext.kotlin_version = '" + KOTLIN_VERSION + "'",
        )
    ],
    "Kotlin legacy ext (build.gradle)",
)

kotlin_declared = False
for path in ("android/settings.gradle", "android/build.gradle"):
    text = read(path) or ""
    if "org.jetbrains.kotlin.android" in text and KOTLIN_VERSION in text:
        kotlin_declared = True
    if "ext.kotlin_version" in text and KOTLIN_VERSION in text:
        kotlin_declared = True
if not kotlin_declared:
    errors.append(f"Kotlin version not verified after patch ({KOTLIN_VERSION})")

# Re-read for the report (Kotlin patch ran after the earlier snapshot)
settings_content = read("android/settings.gradle") or settings_content

# ---------------------------------------------------------------
# 4) + 5) app compileSdk 35 + build-tools 35.0.0
# ---------------------------------------------------------------
# Template uses `compileSdk = flutter.compileSdkVersion` - replace the
# whole assignment with a literal 35.
app_gradle = read("android/app/build.gradle")
if app_gradle is None:
    errors.append("app/build.gradle not found")
else:
    new_app, n_sdk = re.subn(
        r"compileSdk\s*=\s*(?:flutter\.compileSdkVersion|\d+)",
        "compileSdk = " + COMPILE_SDK,
        app_gradle,
    )
    # buildToolsVersion: add right after compileSdk if absent
    if "buildToolsVersion" not in new_app:
        marker = "compileSdk = " + COMPILE_SDK
        insert = marker + '\n    buildToolsVersion = "' + BUILD_TOOLS + '"'
        new_app = new_app.replace(marker, insert, 1)
    else:
        new_app, _ = re.subn(
            r"buildToolsVersion\s*[=:]?\s*[\"'][^\"']*[\"']",
            'buildToolsVersion = "' + BUILD_TOOLS + '"',
            new_app,
        )
    if n_sdk > 0 or ("compileSdk = " + COMPILE_SDK) in app_gradle:
        write("android/app/build.gradle", new_app)
    else:
        errors.append("compileSdk patch did not match app/build.gradle")

verify_app = read("android/app/build.gradle") or ""
if f"compileSdk = {COMPILE_SDK}" not in verify_app:
    errors.append("compileSdk not verified in app/build.gradle")
if BUILD_TOOLS not in verify_app:
    errors.append("buildToolsVersion not verified in app/build.gradle")

# ---------------------------------------------------------------
# 6) Force Kotlin 1.9.24 on every subproject (root build.gradle)
# ---------------------------------------------------------------
root_gradle = read("android/build.gradle")
KOTLIN_FORCE_BLOCK = """

// VCTCrypt CI: force every subproject onto Kotlin {ver}.
// Flutter plugins ship legacy buildscript blocks with old Kotlin
// (e.g. desktop_drop 0.4.4 -> 1.6.10) that cannot read modern
// androidx/kotlin-stdlib metadata. Buildscript classpath conflict
// resolution keeps the highest version, so this overrides them all.
subprojects {{
    buildscript {{
        repositories {{
            google()
            mavenCentral()
        }}
        dependencies {{
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:{ver}"
        }}
    }}
}}
""".format(ver=KOTLIN_VERSION)

if root_gradle is None:
    errors.append("android/build.gradle not found")
elif "vctcrypt-kotlin-force" not in root_gradle:
    write(
        "android/build.gradle",
        root_gradle
        + "\n// vctcrypt-kotlin-force\n"
        + KOTLIN_FORCE_BLOCK,
    )
root_verify = read("android/build.gradle") or ""
if KOTLIN_VERSION not in root_verify or "kotlin-gradle-plugin" not in root_verify:
    errors.append("Kotlin subproject force block not verified")

# ---------------------------------------------------------------
# 7) R8 minify + shrink (anti-decompilation)
# ---------------------------------------------------------------
r8_ok = patch(
    "android/app/build.gradle",
    [
        (r"minifyEnabled\s+false", "minifyEnabled true"),
        (r"shrinkResources\s+false", "shrinkResources true"),
    ],
    "R8 (app/build.gradle)",
)

# Tolerate mixed Kotlin JVM targets across plugin modules
gp = read("android/gradle.properties") or ""
if "kotlin.jvm.target.validation.mode" not in gp:
    with open("android/gradle.properties", "a", encoding="utf-8") as f:
        f.write("\n# VCTCrypt CI: tolerate mixed Kotlin JVM targets\n")
        f.write("kotlin.jvm.target.validation.mode=warning\n")

# ---------------------------------------------------------------
# Report
# ---------------------------------------------------------------
print("=== fix_android.py report ===")
print(f"Gradle wrapper -> {GRADLE_VERSION}: " + ("OK" if wrapper_ok else "FAILED"))
print(f"AGP -> {AGP_VERSION}: " + ("OK" if agp_ok else "FAILED"))
print(f"Kotlin -> {KOTLIN_VERSION}: " + ("OK" if kotlin_declared else "FAILED"))
print(f"compileSdk -> {COMPILE_SDK}: OK")
print(f"buildToolsVersion -> {BUILD_TOOLS}: OK")
print(f"subprojects Kotlin force: OK")
print(f"R8 minify/shrink: " + ("patched" if r8_ok else "already set / not found"))

print("\n--- settings.gradle (plugin versions) ---")
for line in (settings_content or "(missing)").splitlines():
    if "kotlin" in line.lower() or "com.android.application" in line:
        print("   " + line.rstrip())

print("\n--- gradle-wrapper.properties ---")
for line in wrapper_content.splitlines():
    if "distributionUrl" in line:
        print("   " + line.rstrip())

if errors:
    print("\nERRORS:", file=sys.stderr)
    for e in errors:
        print("  - " + e, file=sys.stderr)
    sys.exit(1)

print("\nAll critical patches applied and verified.")
